name: tasks
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Package UI Design
  intl: ^0.20.2

  # Package Eception Handling
  logger: ^2.5.0

  # Package Database
  sqflite: ^2.4.2

  # Package Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # Package Sate Management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0


  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/